build:
  image: node:4-onbuild
  commands:
    - npm install
    - npm test

cache:
  mount:
    - node_modules


publish:
  docker:
    registry: quay.io
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: $$QUAY_USER
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: quay.io/ukhomeofficedigital/levweb
    tag:
      - latest
      - "$$BUILD_NUMBER"
    when:
      branch: master
    branch: master
