pipeline:

  build:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t lev-web .
      - docker build -t lev-web-testing -f Dockerfile-testing .
      - docker run -d --net host lev-web
      - sleep 5
      - docker run --net host lev-web-testing
    when:
      branch: master
      event: [pull_request, push]

  push_image:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - PACKAGE_VERSION=$(grep version package.json | head -1 | awk -F ":" '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
      - TAG="v${PACKAGE_VERSION}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT}"
      - REPO="artifactory-internal.digital.homeoffice.gov.uk"
      - BASE="/"
      - NAME="lev-web"
      - FULL_NAME="${REPO}${BASE}${NAME}"
      - DOCKER_USERNAME="lev-web-robot"
      - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" "${REPO}"
      - docker tag lev-web "${FULL_NAME}:${TAG}"
      - docker tag lev-web "${FULL_NAME}:latest"
      - docker push "${FULL_NAME}:${TAG}"
      - docker push "${FULL_NAME}:latest"
      - E2E_NAME="${FULL_NAME}-e2e"
      - docker build -t lev-web-e2e -f Dockerfile-e2e .
      - docker tag lev-web-e2e "${E2E_NAME}:${TAG}"
      - docker tag lev-web-e2e "${E2E_NAME}:latest"
      - docker push "${E2E_NAME}:${TAG}"
      - docker push "${E2E_NAME}:latest"
    when:
      branch: master
      event: push

  deploy_image:
    image: quay.io/ukhomeofficedigital/kd:latest
    commands:
      - PACKAGE_VERSION=$(grep version package.json | head -1 | awk -F ":" '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
      - TAG="v${PACKAGE_VERSION}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT}"
      - REPO="artifactory-internal.digital.homeoffice.gov.uk"
      - BASE="/"
      - NAME="lev-web"
      - FULL_NAME="${REPO}${BASE}${NAME}"
      - kubectl="kubectl --insecure-skip-tls-verify --server=${KUBE_SERVER} --namespace=${KUBE_NAMESPACE} --token=${KUBE_TOKEN}"
      - ${kubectl} set image deployment/${KUBE_DEPLOYMENT} "${KUBE_CONTAINER}=${FULL_NAME}:${TAG}"
      - ${kubectl} rollout status deployment/${KUBE_DEPLOYMENT}
    when:
      branch: master
      event: push

  e2e_test:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - PACKAGE_VERSION=$(grep version package.json | head -1 | awk -F ":" '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
      - TAG="v${PACKAGE_VERSION}-${DRONE_BUILD_NUMBER}-${DRONE_COMMIT}"
      - REPO="artifactory-internal.digital.homeoffice.gov.uk"
      - BASE="/"
      - NAME="lev-web"
      - FULL_NAME="${REPO}${BASE}${NAME}-e2e"
      - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" "${REPO}"
      - docker run --rm -e "ENV=dev" -e "TEST_URL=${DEV_URL}" -e "USERNAME=${DEV_USERNAME}" -e "PASSWORD=${DEV_PASSWORD}" "${E2E_NAME}:${TAG}"
    when:
      branch: master
      event: push

services:
  mock:
    image: quay.io/ukhomeofficedigital/lev-api-mock:v1.2.0-327-246830c0d3e05b5f7f405803e044974848268bdc
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
