build:
  image: node:4.2.2
  commands:
      - npm install --quiet
      - npm run install:mockapi
      - npm test

publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    registry: quay.io
    username: $$QUAY_USER
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: quay.io/ukhomeofficedigital/lev-web
    storage_driver: overlay
    tag:
      - latest
      - "$$BUILD_NUMBER"
    when:
      branch: master
      
deploy:
  kubernetes:
    image: quay.io/ukhomeofficedigital/drone-kubernetes
    replicationcontrollers:
      - kube/dev/controller.yaml
    services: []
    token: $$TOKEN
    apiserver: $$APISERVER
    namespace:  lev-web-dev
    tag: "$$BUILD_NUMBER"
    when:
      branch: master
