build:
  image: node:4.2.2
  commands:
      - npm install --quiet
      - npm test

publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    registry: quay.io
    username: $$QUAY_USER
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: quay.io/ukhomeofficedigital/lev-web
    storage_driver: overlay
    when:
      branch: master
    tag:
      - latest
      - "$$BUILD_NUMBER"
