language: node_js
 
node_js:
  - 4
  - 4.4.7
  - 6

matrix:
  allow_failures:
    - node_js: 4
    - node_js: 6
  fast_finish: true

cache:
  directories:
    - node_modules
    - api/mock/node_modules

before_install:
  - npm run install:mockapi
  - rm -rf node_modules/node-sass

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env: CXX="g++-4.8" CC="gcc-4.8"
