language: node_js
node_js:
  - "4"
  - "6"

cache:
  directories:
    - node_modules
    - api/mock/node_modules

before_install:
  - npm run install:mockapi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env: CXX="g++-4.8" CC="gcc-4.8"
