language: node_js

sudo: required

services:
  - docker
 
node_js:
  - 6.9.1
  - 6

matrix:
  allow_failures:
    - node_js: 6
  fast_finish: true

cache:
  directories:
    - node_modules

before_install:
  - npm cache clean
  - rm -rf node_modules/node-sass
