version: "3"
services:
  lev-web:
    build:
      context: .
      dockerfile: Dockerfile-build
    environment:
      NODE_ENV: dev
      API_HOST: mock-api
      API_PORT: 8080
    volumes:
      - .:/app
    ports:
      - "8001:8001"
  mock-api:
    image: quay.io/ukhomeofficedigital/lev-api:0.18
    environment:
      MOCK: "true"

