FROM node:12

RUN addgroup --system app \
 && adduser --system --home /app/ --uid 31337 --ingroup app app \
 && chown -R app:app /app/

USER app
WORKDIR /app
ENV NODE_ENV ci

COPY *node_modules/ package.json .snyk /app/
RUN npm install > .npm-install.log 2>&1 \
 && rm .npm-install.log \
 || ( EC=$?; cat .npm-install.log; exit $EC )

COPY . /app

RUN npm run postinstall

USER 31337
ENTRYPOINT [ "npm", "run" ]
CMD [ "test:ci" ]
