version: "3"
services:
  api:
    image: quay.io/ukhomeofficedigital/lev-api:0.9
    environment:
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=8080
      - POSTGRES_USER=lev
      - POSTGRES_PASSWORD=lev
      - POSTGRES_HOST=postgres
      - POSTGRES_ADMIN_USER=root
      - POSTGRES_ADMIN_PASSWORD=root
      - POSTGRES_SSL=FALSE
    ports:
      - "80:8080"
  postgres:
    image: postgres:9-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=lev
    ports:
      - "5432:5432"
  wrangler:
    image: docker.digital.homeoffice.gov.uk/lev-wrangler:latest
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=lev
      - APP_USER=lev
      - APP_PASSWORD=lev
      - SYMDS_USER=lev
      - SYMDS_PASSWORD=lev
      - ADD_TEST_DATA=yes
