env:
  mocha: true
globals:
  chai: true
  cy: true
  expect: true
  sinon: true
  should: true
  assert: true
rules:
  func-names: 0
  max-nested-callbacks: 0
  no-unused-expressions: 0
  no-process-env: 0
  no-console: 0
