---
apiVersion: v1
kind: ReplicationController
metadata:
  name: lev-web-dev
  labels:
    name: lev-web-dev
  namespace: lev-web-dev
spec:
  replicas: 1
  selector:
    name: lev-web-dev
  template:
    metadata:
      labels:
        name: lev-web-dev
    spec:
      containers:
      - name: lev-web-dev
        image: quay.io/ukhomeofficedigital/lev-web:{{ .TAG }}
        imagePullPolicy: Always
        env:
          - name: API_HOST
            value: lev-api-dev.lev-api-dev
          - name: API_PORT
            value: "8888"
        resources:
          limits:
            memory: "256Mi"
