apiVersion: v1
kind: Service
metadata:
  name: lev-web-preprod
  labels:
    name: lev-web-preprod
    role: service
  namespace: lev-web-preprod
spec:
  type: NodePort
  ports:
  - name: http
    port: 8001
    nodePort: 30201
  selector:
    name: lev-web-preprod
