'use strict';

module.exports = {
  "location": {
    "name": "Test District, Test Subdistrict, Reading",
    "administrativeArea": "Reading",
    "subDistrict": "Test Subdistrict",
    "nameQualifier": "generated by concatenating registrationDistrict, subDistrict and administrativeArea",
    "registrationDistrict": "Test District"
  },
  "subjects": {
    "child": {
      "originalName": {
        "givenName": "Tester",
        "surname": "Solo",
        "fullName": "Tester Solo",
        "qualifier": "generated from prepending forename to surname"
      },
      "name": {
        "givenName": "Brandon",
        "surname": "Solo",
        "fullName": "Brandon Solo",
        "qualifier": "generated from prepending forename to surname"
      },
      "dateOfBirth": "29/02/2000",
      "sex": "Male",
      "birthplace": "Test Address"
    },
    "father": {
      "name": {
        "givenName": "Dad",
        "surname": "Solo",
        "fullName": "Dad Solo",
        "qualifier": "generated from prepending forename to surname"
      },
      "birthplace": "Test Birthplace"
    },
    "mother": {
      "name": {
        "givenName": "Mum",
        "surname": "Solo",
        "fullName": "Mum Solo",
        "qualifier": "generated from prepending forename to surname"
      },
      "birthplace": "Test Birthplace",
      "maidenSurname": "prev-Solo"
    },
    "informant": {
      "name": {

      },
      "qualification": "Mother",
      "signature": "Mary Manzarek"
    }
  },
  "systemNumber": 999999910,
  "id": 999999910,
  "date": "10/10/2014",
  "status": {
    "courtOrder": "None",
    "fictitiousBirth": false,
    "cancelled": false,
    "blockedRegistration": false,
    "cautionMark": false,
    "reRegistered": "None"
  },
  "previousRegistration": {
  }
};